use crate::models::ReportSummary;
use std::io;

/// Generate a Markdown report string from a ReportSummary.
pub fn generate_markdown_report(summary: &ReportSummary) -> io::Result<String> {
    let mut md = String::new();

    md.push_str("# SecGuard RS Detection Report\n\n");
    md.push_str(&format!("**Generated by:** {}\n\n", summary.generated_by));
    md.push_str(&format!("**Version:** {}\n\n", summary.version));
    md.push_str(&format!("**Input Summary:** {}\n\n", summary.input_summary));
    md.push_str(&format!("**Finding Count:** {}\n\n", summary.finding_count));

    if summary.findings.is_empty() {
        md.push_str("## Findings\n\nNo detections found.\n");
        return Ok(md);
    }

    md.push_str("## Findings\n\n");
    md.push_str("| # | Detection ID | Timestamp | Rule ID | Severity | Entity | Summary |");
    md.push_str("\n|---|-------------|-----------|---------|----------|--------|---------|\n");

    for (i, f) in summary.findings.iter().enumerate() {
        let line = format!(
            "| {} | {} | {} | {} | {} | {} | {} |\n",
            i + 1,
            escape_md(&f.detection_id),
            escape_md(&f.timestamp),
            escape_md(&f.rule_id),
            escape_md(&f.severity),
            escape_md(&f.entity),
            escape_md(&f.summary),
        );
        md.push_str(&line);
    }

    md.push_str("\n### Evidence Details\n\n");
    for (i, f) in summary.findings.iter().enumerate() {
        md.push_str(&format!("**{}** - {} ({})", i + 1, f.detection_id, f.rule_id));
        md.push_str(&format!("\n\n- **Entity:** {}\n", escape_md(&f.entity)));
        md.push_str(&format!("- **Severity:** {}\n", escape_md(&f.severity)));
        md.push_str(&format!("- **Summary:** {}\n", escape_md(&f.summary)));
        md.push_str(&format!("- **Evidence:** {}\n", escape_md(&f.evidence)));
        md.push_str(&format!("- **Recommendation:** {}\n\n", escape_md(&f.recommendation)));
    }

    md.push_str("---\n\n*Report generated by SecGuard RS v");
    md.push_str(&summary.version);
    md.push_str("*\n");

    Ok(md)
}

/// Escape special Markdown characters.
fn escape_md(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ").replace('\r', "")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{Detection, ReportSummary};

    fn sample_findings() -> Vec<Detection> {
        vec![
            Detection {
                detection_id: "DET-001".to_string(),
                timestamp: "2025-06-01T10:00:00Z".to_string(),
                rule_id: "SG-AUTH-001".to_string(),
                severity: "high".to_string(),
                entity: "admin@10.0.0.5".to_string(),
                summary: "Brute force detected".to_string(),
                evidence: "5 failures in 10 min".to_string(),
                recommendation: "Lock account".to_string(),
            },
        ]
    }

    #[test]
    fn test_markdown_empty_findings() {
        let summary = ReportSummary::new("test_input.csv".to_string(), vec![]);
        let md = generate_markdown_report(&summary).unwrap();
        assert!(md.contains("No detections found"));
        assert!(md.contains("**Finding Count:** 0"));
    }

    #[test]
    fn test_markdown_with_findings() {
        let summary = ReportSummary::new("test_input.csv".to_string(), sample_findings());
        let md = generate_markdown_report(&summary).unwrap();
        assert!(md.contains("DET-001"));
        assert!(md.contains("SG-AUTH-001"));
        assert!(md.contains("high"));
        assert!(md.contains("Brute force detected"));
    }

    #[test]
    fn test_markdown_table_header() {
        let summary = ReportSummary::new("test.csv".to_string(), sample_findings());
        let md = generate_markdown_report(&summary).unwrap();
        assert!(md.contains("| # | Detection ID |"));
        assert!(md.contains("| 1 | DET-001 |"));
    }

    #[test]
    fn test_markdown_generated_by() {
        let summary = ReportSummary::new("test.csv".to_string(), vec![]);
        let md = generate_markdown_report(&summary).unwrap();
        assert!(md.contains("SecGuard RS"));
        assert!(md.contains("1.0.0"));
    }

    #[test]
    fn test_markdown_special_chars_escaped() {
        let findings = vec![Detection {
            detection_id: "DET|1".to_string(),
            timestamp: "2025-01-01T00:00:00Z".to_string(),
            rule_id: "RULE|1".to_string(),
            severity: "medium".to_string(),
            entity: "test|entity".to_string(),
            summary: "pipe | char test".to_string(),
            evidence: "evidence".to_string(),
            recommendation: "remediate".to_string(),
        }];
        let summary = ReportSummary::new("test.csv".to_string(), findings);
        let md = generate_markdown_report(&summary).unwrap();
        assert!(md.contains("\\|"));
    }
}